/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author Carla Daniela
 */
public class SegundaVentana extends javax.swing.JFrame {

    /**
     * Creates new form SegundaVentana
     */
    public SegundaVentana() {
        initComponents();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EVALUACIONES = new javax.swing.JButton();
        HORARIO = new javax.swing.JButton();
        CURSOS = new javax.swing.JButton();
        INGRESAR = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        MENU = new javax.swing.JButton();
        Fond2 = new javax.swing.JLabel();
        Fond1 = new javax.swing.JLabel();
        Fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EVALUACIONES.setBackground(new java.awt.Color(255, 102, 102));
        EVALUACIONES.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        EVALUACIONES.setForeground(new java.awt.Color(255, 255, 255));
        EVALUACIONES.setText("NOTAS");
        EVALUACIONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EVALUACIONESActionPerformed(evt);
            }
        });
        getContentPane().add(EVALUACIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, 40));

        HORARIO.setBackground(new java.awt.Color(255, 102, 102));
        HORARIO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HORARIO.setForeground(new java.awt.Color(255, 255, 255));
        HORARIO.setText("HORARIO");
        HORARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HORARIOActionPerformed(evt);
            }
        });
        getContentPane().add(HORARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, 40));

        CURSOS.setBackground(new java.awt.Color(255, 102, 102));
        CURSOS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CURSOS.setForeground(new java.awt.Color(255, 255, 255));
        CURSOS.setText("CURSOS");
        CURSOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CURSOSActionPerformed(evt);
            }
        });
        getContentPane().add(CURSOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 160, 40));

        INGRESAR.setBackground(new java.awt.Color(255, 102, 102));
        INGRESAR.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        INGRESAR.setForeground(new java.awt.Color(255, 255, 255));
        INGRESAR.setText("INGRESAR");
        INGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESARActionPerformed(evt);
            }
        });
        getContentPane().add(INGRESAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 160, 40));

        SALIR.setBackground(new java.awt.Color(255, 51, 51));
        SALIR.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SALIR.setForeground(new java.awt.Color(255, 255, 255));
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 160, 40));

        MENU.setBackground(new java.awt.Color(255, 153, 153));
        MENU.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MENU.setForeground(new java.awt.Color(255, 255, 255));
        MENU.setText("MENÚ");
        getContentPane().add(MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 50));

        Fond2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/leon.png"))); // NOI18N
        getContentPane().add(Fond2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 240, 300));

        Fond1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/barradurazno (1).png"))); // NOI18N
        getContentPane().add(Fond1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        Fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondodurazno (1).png"))); // NOI18N
        getContentPane().add(Fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESARActionPerformed
        new INGRESAR().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_INGRESARActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    private void HORARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HORARIOActionPerformed
        new HORARIOS().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HORARIOActionPerformed

    private void EVALUACIONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EVALUACIONESActionPerformed
        new EVALUACIONES().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EVALUACIONESActionPerformed

    private void CURSOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CURSOSActionPerformed
        new CURSOS().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CURSOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundaVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CURSOS;
    private javax.swing.JButton EVALUACIONES;
    private javax.swing.JLabel Fond;
    private javax.swing.JLabel Fond1;
    private javax.swing.JLabel Fond2;
    private javax.swing.JButton HORARIO;
    private javax.swing.JButton INGRESAR;
    private javax.swing.JButton MENU;
    private javax.swing.JButton SALIR;
    // End of variables declaration//GEN-END:variables
}
